### ISSUE TITLE
Add default `knownRegions` key to silence a new Xcode 10.2 warning

### ISSUE THREAD

**Issue by tatewake** [refack/GYP#39]
### What steps will reproduce the problem?

1. In Xcode 10.2, a new warning is shown for all gyp-generated projects stating: "Enable Base Internationalization"
2. This is because gyp has never generated the `knownRegions` key, and Xcode has always (previously) silently created it
3. Clicking to "fix" the warning in Xcode will auto-generate the `knownRegions` key, but any time an xcodeproj file is regenerated (and Xcode rebooted) the warning will yet again show and need to be "fixed"

### What is the expected output? What do you see instead?

One would hope that gyp would auto-generate a default key, but

### What version of the product are you using? On what operating system?

macOS Mojave 10.14.4 using an up-to-date GYP as of April 1, 2019

### Please provide any additional information below.

The fix proposed for this ticket is to add the following line to xcodeproj_file.py somewhere after line 2582 (the "_schema.update" line):

     'knownRegions':           [0, list,                 0, 1, ['en', 'Base']],

This will silence the error and have the same effect of the "Xcode fix."

However, it would probably be a good idea to have a key from within gyp that the user could configure since one could imagine adding "more languages" to the `knownRegions`, as well as it already being possible to change this key from within Xcode itself (and not possible to do this within the gyp file currently.)

**Comment by tatewake** [comment]
Since this project seems to no longer be updated, I'm closing my PR.

**Comment by Croydon** [comment]
For anyone finding this and wondering, I think the best choice is https://github.com/nodejs/gyp-next
